name: 2 Flujo de trabajo para la integraci贸n continua
on:
  workflow_dispatch:
  push:
    branches: [ frarosrap ]
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo el c贸digo
        run: |
          chmod +x gradlew        
          ./gradlew jar
      - name: mostrando uvus
        run: echo 'frarosrap'                  
  Test:
    runs-on: ubuntu-latest
    needs: Build
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Probando el c贸digo
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: mostrando uvus
        run: echo 'frarosrap'   
  Publishing:
    runs-on: ubuntu-latest
    needs: Test
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.TOKEN }}
      GITHUB_OAUTH: ${{ secrets.TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Publicando el c贸digo
        run: |
          chmod +x gradlew        
          ./gradlew publish
      - name: mostrando uvus
        run: echo 'frarosrap' 
